"""Unit tests for dasmos.core.labels.

Covers the data layer only — :class:`Label` as pure data, the
:class:`LabelManager` registry, validation through the registry. The
renderer-coupled methods (string-list emission, inline definition
gathering) from py8dis are deliberately deferred to a later port that
follows the assembler abstraction.
"""

import pytest

from dasmos.core.labels import (
    ExplicitName,
    Label,
    LabelError,
    LabelManager,
    LocalLabel,
)
from dasmos.core.memory import (
    BinaryAddr,
    BinaryLocation,
    Reference,
    ReferenceKind,
    RuntimeAddr,
)
from dasmos.core.move import BASE_MOVE_ID, MoveManager


@pytest.fixture
def mm():
    """A clean MoveManager. Most tests need only the BASE_MOVE_ID."""
    return MoveManager()


@pytest.fixture
def lm(mm):
    return LabelManager(mm)


class TestExplicitName:

    def test_construction_defaults(self):
        n = ExplicitName("foo", is_autogenerated=False)
        assert n.text == "foo"
        assert n.emitted is False
        assert n.priority is None
        assert n.is_autogenerated is False

    def test_priority_is_carried(self):
        n = ExplicitName("foo", is_autogenerated=True, priority=5)
        assert n.priority == 5
        assert n.is_autogenerated is True


class TestLocalLabel:

    def test_construction(self):
        ll = LocalLabel("loop", 0x8000, 0x8010)
        assert ll.name == "loop"
        assert ll.start_addr == 0x8000
        assert ll.end_addr == 0x8010


class TestLabel:
    """Label is pure data; behaviour-tested in isolation from any registry."""

    def test_construction_records_runtime_addr(self):
        lab = Label(RuntimeAddr(0x8000))
        assert lab.runtime_addr == RuntimeAddr(0x8000)
        assert lab.references == []
        assert lab.description is None
        assert lab.length is None
        assert lab.group is None
        assert lab.access is None
        assert lab.definable_inline is True

    def test_add_explicit_name_buckets_by_move_id(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.add_explicit_name(
            ExplicitName("foo", is_autogenerated=False), move_id=0,
        )
        lab.add_explicit_name(
            ExplicitName("bar", is_autogenerated=False), move_id=1,
        )
        assert [n.text for n in lab.explicit_names[0]] == ["foo"]
        assert [n.text for n in lab.explicit_names[1]] == ["bar"]

    def test_add_explicit_name_is_idempotent_on_duplicate(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.add_explicit_name(
            ExplicitName("foo", is_autogenerated=False), move_id=0,
        )
        lab.add_explicit_name(
            ExplicitName("foo", is_autogenerated=False), move_id=0,
        )
        assert [n.text for n in lab.explicit_names[0]] == ["foo"]

    def test_add_local_label(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.add_local_label(LocalLabel("loop", 0x8000, 0x8010), move_id=0)
        assert lab.local_labels[0][0].name == "loop"

    def test_add_expression_appends(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.add_expression("base + 4", move_id=0)
        lab.add_expression("base + 8", move_id=0)
        assert lab.expressions[0] == ["base + 4", "base + 8"]

    def test_add_expression_is_idempotent_on_duplicate(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.add_expression("base + 4", move_id=0)
        lab.add_expression("base + 4", move_id=0)
        assert lab.expressions[0] == ["base + 4"]

    def test_add_reference_collects_binary_locations(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.add_reference(BinaryLocation(0x9000, BASE_MOVE_ID))
        lab.add_reference(BinaryLocation(0x9010, BASE_MOVE_ID))
        assert len(lab.references) == 2

    def test_is_only_an_expression(self):
        lab = Label(RuntimeAddr(0x8000))
        assert not lab.is_only_an_expression()
        lab.add_expression("base + 4", move_id=0)
        assert lab.is_only_an_expression()
        lab.add_explicit_name(
            ExplicitName("foo", is_autogenerated=False), move_id=0,
        )
        assert not lab.is_only_an_expression()

    def test_all_names_returns_flat_set(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.add_explicit_name(
            ExplicitName("foo", is_autogenerated=False), move_id=0,
        )
        lab.add_explicit_name(
            ExplicitName("bar", is_autogenerated=False), move_id=1,
        )
        lab.add_local_label(LocalLabel("loop", 0x8000, 0x8010), move_id=0)
        lab.add_expression("base + 4", move_id=0)
        assert lab.all_names() == {"foo", "bar", "loop", "base + 4"}

    def test_all_names_by_move_id(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.add_explicit_name(
            ExplicitName("foo", is_autogenerated=False), move_id=0,
        )
        lab.add_explicit_name(
            ExplicitName("bar", is_autogenerated=False), move_id=1,
        )
        result = lab.all_names_by_move_id()
        assert result[0] == {"foo"}
        assert result[1] == {"bar"}

    def test_get_already_emitted_name_returns_first_emitted(self):
        lab = Label(RuntimeAddr(0x8000))
        n1 = ExplicitName("foo", is_autogenerated=False)
        n2 = ExplicitName("bar", is_autogenerated=False)
        lab.add_explicit_name(n1, move_id=0)
        lab.add_explicit_name(n2, move_id=0)
        assert lab.get_already_emitted_name() is None
        n2.emitted = True
        assert lab.get_already_emitted_name() == "bar"

    def test_notify_emit_opportunity_collects_unique_move_ids(self):
        lab = Label(RuntimeAddr(0x8000))
        lab.notify_emit_opportunity(0)
        lab.notify_emit_opportunity(1)
        lab.notify_emit_opportunity(0)
        assert lab.emit_opportunities == {0, 1}


class TestLabelManagerAddLabel:

    def test_add_label_creates_label_at_runtime_addr(self, lm):
        lm.add_label(0x8000, "foo")
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert lab is not None
        assert lab.runtime_addr == RuntimeAddr(0x8000)
        assert "foo" in lab.all_names()

    def test_add_label_extends_existing_label(self, lm):
        lm.add_label(0x8000, "foo")
        lm.add_label(0x8000, "bar")
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert lab.all_names() == {"foo", "bar"}

    def test_add_label_default_move_id_is_base(self, lm):
        lm.add_label(0x8000, "foo")
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert "foo" in {n.text for n in lab.explicit_names[BASE_MOVE_ID]}

    def test_add_label_uses_active_move_when_no_id_given(self, lm, mm):
        m1 = mm.add_move(RuntimeAddr(0x70), BinaryAddr(0x1900), 10)
        with m1:
            lm.add_label(0x8000, "foo")
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert "foo" in {n.text for n in lab.explicit_names[m1._move_id]}

    def test_add_label_explicit_move_id_overrides_active(self, lm, mm):
        m1 = mm.add_move(RuntimeAddr(0x70), BinaryAddr(0x1900), 10)
        with m1:
            lm.add_label(0x8000, "foo", move_id=BASE_MOVE_ID)
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert "foo" in {n.text for n in lab.explicit_names[BASE_MOVE_ID]}

    def test_add_label_rejects_invalid_move_id(self, lm):
        with pytest.raises(LabelError, match="move id"):
            lm.add_label(0x8000, "foo", move_id=99)

    def test_add_label_rejects_non_identifier_name(self, lm):
        with pytest.raises(LabelError, match="identifier"):
            lm.add_label(0x8000, "foo bar")
        with pytest.raises(LabelError, match="identifier"):
            lm.add_label(0x8000, "1foo")
        with pytest.raises(LabelError, match="identifier"):
            lm.add_label(0x8000, "")

    def test_add_label_carries_metadata(self, lm):
        lm.add_label(
            0x8000, "foo",
            description="A test label.",
            length=4,
            group="test",
            access="r",
        )
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert lab.description == "A test label."
        assert lab.length == 4
        assert lab.group == "test"
        assert lab.access == "r"


class TestLabelManagerLookup:

    def test_get_label_unknown_returns_none(self, lm):
        assert lm.get_label(RuntimeAddr(0x8000)) is None

    def test_addr_for_name_finds_explicit_name(self, lm):
        lm.add_label(0x8000, "foo")
        lm.add_label(0x9000, "bar")
        assert lm.addr_for_name("foo") == RuntimeAddr(0x8000)
        assert lm.addr_for_name("bar") == RuntimeAddr(0x9000)

    def test_addr_for_name_finds_local_label(self, lm):
        lm.add_local_label(0x8000, "loop", 0x8000, 0x8010)
        assert lm.addr_for_name("loop") == RuntimeAddr(0x8000)

    def test_addr_for_name_unknown_returns_none(self, lm):
        assert lm.addr_for_name("never_added") is None

    def test_iter_labels(self, lm):
        lm.add_label(0x8000, "foo")
        lm.add_label(0x9000, "bar")
        addrs = sorted(int(addr) for addr in lm)
        assert addrs == [0x8000, 0x9000]

    def test_contains(self, lm):
        lm.add_label(0x8000, "foo")
        assert RuntimeAddr(0x8000) in lm
        assert RuntimeAddr(0x9000) not in lm


class TestLabelManagerLocalLabel:

    def test_add_local_label(self, lm):
        lm.add_local_label(0x8000, "loop", 0x8000, 0x8010)
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert lab.local_labels[BASE_MOVE_ID][0].name == "loop"

    def test_add_local_label_rejects_non_identifier(self, lm):
        with pytest.raises(LabelError, match="identifier"):
            lm.add_local_label(0x8000, "no spaces", 0x8000, 0x8010)


class TestLabelManagerExpression:

    def test_add_expression(self, lm):
        lm.add_expression(0x8000, "base + 4")
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert "base + 4" in lab.expressions[BASE_MOVE_ID]

    def test_add_expression_rejects_simple_identifier(self, lm):
        # An identifier is a name, not an expression.
        with pytest.raises(LabelError, match="expression"):
            lm.add_expression(0x8000, "foo")


class TestLabelManagerReference:

    def test_add_reference(self, lm):
        lm.add_reference(0x8000, BinaryLocation(0x9000, BASE_MOVE_ID))
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert lab.references == [
            Reference(BinaryLocation(0x9000, BASE_MOVE_ID), ReferenceKind.DIRECT),
        ]

    def test_add_reference_defaults_to_direct_kind(self, lm):
        lm.add_reference(0x8000, BinaryLocation(0x9000, BASE_MOVE_ID))
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert lab.references[0].kind is ReferenceKind.DIRECT
        assert int(lab.references[0].binary_addr) == 0x9000

    def test_add_reference_records_indexed_base_kind(self, lm):
        lm.add_reference(
            0x8000, BinaryLocation(0x9000, BASE_MOVE_ID),
            ReferenceKind.INDEXED,
        )
        lab = lm.get_label(RuntimeAddr(0x8000))
        assert lab.references[0].kind is ReferenceKind.INDEXED
        assert not lab.has_direct_reference()
        assert lab.indexed_base_reference_count() == 1


class TestLabelManagerIndependence:

    def test_two_managers_share_no_state(self):
        # The justification for the rewrite — module-level `labels`
        # dict in py8dis prevented this property.
        mm_a = MoveManager()
        mm_b = MoveManager()
        lm_a = LabelManager(mm_a)
        lm_b = LabelManager(mm_b)
        lm_a.add_label(0x8000, "foo")
        assert lm_a.get_label(RuntimeAddr(0x8000)) is not None
        assert lm_b.get_label(RuntimeAddr(0x8000)) is None
        assert lm_b.addr_for_name("foo") is None
