"""Per-disassembly configuration.

A single :class:`Config` dataclass owned by the
:class:`~dasmos.Disassembler` orchestration class. Two ``Config``
instances are independent, which is the property the orchestration
layer needs.

The configured renderer instance lives on the Disassembler rather than
in this dataclass; ``cmos`` (whether the active CPU is CMOS-flavored)
sits here as a convenience for renderer plug-ins that emit a ``cpu``
directive, but is really a property of the active CPU plug-in.
"""

from dataclasses import dataclass


@dataclass
class Config:
    """Per-disassembly configuration knobs.

    All fields are mutable on the instance.
    """

    # Casing
    lower_case: bool = True

    # Hex dumps in the inline comment column
    hex_dump: bool = True
    hex_dump_max_bytes: int = 3
    hex_dump_show_ascii: bool = True

    # References (the back-pointer machinery)
    label_references: bool = True

    # Layout
    inline_comment_column: int = 70
    word_wrap_comment_column: int = 87
    indent_string: str = " " * 4

    # Loop heuristics
    indent_loops: bool = False
    loop_limit: int = 32

    # Block separation
    blank_line_at_block_end: bool = True

    # Diagnostic decoration
    show_cpu_state: bool = False
    show_autogenerated_labels: bool = True
    show_char_literals: bool = True
    show_all_labels: bool = False
    show_cycles: bool = False
    show_stats: bool = True

    # Constant rendering
    constants_are_decimal: bool = True

    # Subroutine banner separators
    subroutine_header: str = "*" * 87
    subroutine_footer: str = "*" * 87

    # Output assertions and labelling policy
    include_assertions: bool = True
    label_return_instructions_numerically: bool = True

    # CPU flavour hint (kept for assemblers' `cpu` directive — really
    # a property of the active CPU plug-in, but exposed here for
    # convenience).
    cmos: bool = False
