"""Per-disassembly configuration.

py8dis's ``config.py`` carried about 25 module-level
``get_<name>``/``set_<name>`` pairs around private module attributes.
The dasmos rewrite replaces them with a single :class:`Config`
dataclass that the :class:`~dasmos.Disassembler` orchestration class
owns. Two ``Config`` instances are independent, which is the property
the orchestration layer needs.

Two settings from py8dis's config module that belong elsewhere:

- ``_assembler`` (the configured assembler instance) — moves to a
  field on the Disassembler.
- ``_cmos`` (whether the active CPU is CMOS-flavored) — kept here as
  a convenience for assembler plug-ins that emit a ``cpu`` directive,
  but really a property of the active CPU plug-in.
"""

from dataclasses import dataclass


@dataclass
class Config:
    """Per-disassembly configuration knobs.

    All fields are mutable on the instance; defaults match py8dis.
    """

    # Casing
    lower_case: bool = True

    # Hex dumps in the inline comment column
    hex_dump: bool = True
    hex_dump_max_bytes: int = 3
    hex_dump_show_ascii: bool = True

    # References (the back-pointer machinery)
    label_references: bool = True

    # Layout
    inline_comment_column: int = 70
    word_wrap_comment_column: int = 87
    indent_string: str = " " * 4

    # Loop heuristics
    indent_loops: bool = False
    loop_limit: int = 32

    # Block separation
    blank_line_at_block_end: bool = True

    # Diagnostic decoration
    show_cpu_state: bool = False
    show_autogenerated_labels: bool = True
    show_char_literals: bool = True
    show_all_labels: bool = False
    show_cycles: bool = False
    show_stats: bool = True

    # Constant rendering
    constants_are_decimal: bool = True

    # Subroutine banner separators
    subroutine_header: str = "*" * 87
    subroutine_footer: str = "*" * 87

    # Output assertions and labelling policy
    include_assertions: bool = True
    label_return_instructions_numerically: bool = True

    # CPU flavour hint (kept for assemblers' `cpu` directive — really
    # a property of the active CPU plug-in, but exposed here for
    # convenience).
    cmos: bool = False
