"""Label registry for the dasmos disassembler.

A *label* names a runtime address. Each :class:`Label` may carry
multiple explicit names (per move_id), local labels with address
ranges, and reference expressions used at use-sites. The
:class:`LabelManager` is the registry: it owns the
runtime-address → :class:`Label` mapping and is the single point of
validation.

Lifted from py8dis's ``label.py`` (365 lines) and ``labelmanager.py``
(130 lines) with the following design changes:

- All state lives on a :class:`LabelManager` instance — no
  module-level ``labels`` dict. Two managers coexist freely.
- :class:`Label` is now **pure data**. py8dis's ``Label`` mixed model
  and renderer (``gather_inline_label_definitions``,
  ``explicit_definition_string_list``, ``_memory_map_brief``) — those
  methods are deliberately not ported here. Rendering belongs to the
  assembler/formatter layer (see tasks #13 / #14) and will read this
  data layer rather than living inside it.
- All validation lives on the :class:`LabelManager` rather than
  scattered through ``Label`` methods. Names must be Python
  identifiers; expressions must *not* be identifiers (that would be a
  name); move_ids are checked against the injected
  :class:`~dasmos.core.move.MoveManager`.
- Failures raise :class:`LabelError` rather than firing assertions
  or calling ``utils.die``.
- The ``description``-attribute / ``description()``-method name clash
  in py8dis is gone — the debug stringifier was only ever used for
  diagnostics and is dropped in favour of ``__repr__``.
- The default move_id for an add-* call is the topmost active move
  (or BASE_MOVE_ID if none) — same as py8dis but explicitly via the
  injected MoveManager rather than via a module-level
  ``movemanager.active_move_ids``.
"""

from collections import defaultdict
from dataclasses import dataclass, field
from typing import Optional

from dasmos.core.memory import BinaryLocation, RuntimeAddr
from dasmos.core.move import BASE_MOVE_ID, MoveManager
from dasmos.exceptions import DasmosError


class LabelError(DasmosError):
    """Raised on invalid label operations."""


@dataclass
class ExplicitName:
    """A label's primary name and the per-name state the renderer
    consults when emitting the disassembly.
    """

    text: str
    is_autogenerated: bool
    priority: Optional[int] = None
    emitted: bool = False


@dataclass
class LocalLabel:
    """A name that is only valid within a specific address range.

    Used for short-lived labels (e.g. loop targets) that the assembler
    treats as scoped.
    """

    name: str
    start_addr: int
    end_addr: int


class Label:
    """Pure data: everything known about the labels at one runtime address.

    Multiple explicit names, local-label scopes and reference
    expressions are bucketed by ``move_id`` because the same runtime
    address can be reached via different relocations and may want
    different names in each.

    Validation is the :class:`LabelManager`'s job — this class trusts
    its inputs.
    """

    def __init__(self, runtime_addr):
        self.runtime_addr = RuntimeAddr(runtime_addr)
        # Optional memory-map metadata attached via add_label kwargs.
        self.description: str | None = None
        self.length: int | None = None
        self.group: str | None = None
        self.access: str | None = None
        # Sites that reference this label (binary locations of use).
        self.references: list[BinaryLocation] = []
        # Per-move-id collections.
        self.explicit_names: dict[int, list[ExplicitName]] = defaultdict(list)
        self.local_labels: dict[int, list[LocalLabel]] = defaultdict(list)
        self.expressions: dict[int, list[str]] = defaultdict(list)
        # Move-ids at which this label could be emitted inline.
        self.emit_opportunities: set[int] = set()
        # Whether the label can appear inline (vs. as an EQU at the top).
        self.definable_inline: bool = True
        # Required = renderer must always emit this label's definition.
        # Optional = renderer emits only if the label was used (i.e.
        # referenced by an operand somewhere in the disassembly).
        # Set True by any non-optional ``add_label`` / ``add_local_label``
        # / ``add_expression`` call; ``optional_label`` leaves it False.
        # Once True, stays True for the life of the Label.
        self.required: bool = False

    def add_explicit_name(self, name: ExplicitName, move_id: int) -> None:
        if name.text not in self.all_names():
            self.explicit_names[move_id].append(name)

    def add_local_label(self, local_label: LocalLabel, move_id: int) -> None:
        self.local_labels[move_id].append(local_label)

    def add_expression(self, expression: str, move_id: int) -> None:
        if expression not in self.all_names():
            self.expressions[move_id].append(expression)

    def add_reference(self, reference: BinaryLocation) -> None:
        self.references.append(reference)

    def notify_emit_opportunity(self, move_id: int) -> None:
        self.emit_opportunities.add(move_id)

    def all_names(self) -> set[str]:
        """Every name and expression for this label, flattened."""
        result: set[str] = set()
        for name_list in self.explicit_names.values():
            for name in name_list:
                result.add(name.text)
        for ll_list in self.local_labels.values():
            for ll in ll_list:
                result.add(ll.name)
        for expr_list in self.expressions.values():
            result.update(expr_list)
        return result

    def all_names_by_move_id(self) -> dict[int, set[str]]:
        result: dict[int, set[str]] = defaultdict(set)
        for move_id, name_list in self.explicit_names.items():
            for name in name_list:
                result[move_id].add(name.text)
        for move_id, ll_list in self.local_labels.items():
            for ll in ll_list:
                result[move_id].add(ll.name)
        for move_id, expr_list in self.expressions.items():
            result[move_id].update(expr_list)
        return dict(result)

    def is_only_an_expression(self) -> bool:
        """True iff this label has only expression entries."""
        return (
            not self.explicit_names
            and not self.local_labels
            and bool(self.expressions)
        )

    def get_already_emitted_name(self) -> str | None:
        """Return the first explicit name marked emitted, or ``None``."""
        for name_list in self.explicit_names.values():
            for name in name_list:
                if name.emitted:
                    return name.text
        return None

    def __repr__(self) -> str:
        return (
            f"Label(runtime_addr=0x{int(self.runtime_addr):x}, "
            f"names={sorted(self.all_names())})"
        )


def _is_identifier(s: str) -> bool:
    """A label name is a Python-style identifier.

    Simpler / equivalent to py8dis's hand-written ``is_simple_name``.
    """
    return bool(s) and s.isidentifier()


class LabelManager:
    """Registry of labels keyed by runtime address.

    The single point of validation. All ``add_*`` methods route here;
    :class:`Label` itself is dumb data.

    Takes a :class:`~dasmos.core.move.MoveManager` for move-id
    validation and for resolving the default move_id (topmost active,
    or BASE_MOVE_ID).
    """

    def __init__(self, move_manager: MoveManager):
        self._move_manager = move_manager
        self._labels: dict[RuntimeAddr, Label] = {}

    def __contains__(self, runtime_addr) -> bool:
        return RuntimeAddr(runtime_addr) in self._labels

    def __iter__(self):
        return iter(self._labels)

    def items(self):
        return self._labels.items()

    def get_label(self, runtime_addr) -> Label | None:
        return self._labels.get(RuntimeAddr(runtime_addr))

    def addr_for_name(self, name: str) -> RuntimeAddr | None:
        """Find the runtime address of a label by one of its names.

        Linear in total label count — same as py8dis. Fine for a
        one-off lookup; callers needing repeated lookups should
        cache.
        """
        for runtime_addr, label in sorted(self._labels.items()):
            for name_list in label.explicit_names.values():
                for explicit in name_list:
                    if explicit.text == name:
                        return runtime_addr
            for ll_list in label.local_labels.values():
                for ll in ll_list:
                    if ll.name == name:
                        return runtime_addr
        return None

    def add_label(
        self,
        runtime_addr,
        name: str,
        *,
        move_id: int | None = None,
        is_autogenerated: bool = False,
        is_optional: bool = False,
        priority: int | None = None,
        description: str | None = None,
        length: int | None = None,
        group: str | None = None,
        access: str | None = None,
    ) -> Label:
        """Add an explicit-name label (and optional memory-map metadata)
        at ``runtime_addr``.

        ``is_optional=True`` (used by
        :meth:`~dasmos.disassembler.Disassembler.optional_label`) makes
        this *name* optional — the label as a whole is required only
        when at least one ``add_label`` call has registered a required
        name. Once a label is required, it stays required.

        Returns the affected :class:`Label`.
        """
        if not _is_identifier(name):
            raise LabelError(
                f"Label name {name!r} is not a valid identifier "
                f"(must start with letter or underscore, then alnum/underscore)"
            )
        move_id = self._resolve_move_id(move_id)
        label = self._get_or_create(runtime_addr)
        label.add_explicit_name(
            ExplicitName(
                text=name,
                is_autogenerated=is_autogenerated,
                priority=priority,
            ),
            move_id=move_id,
        )
        if not is_optional:
            label.required = True
        # Metadata: only set if provided, so a follow-up
        # add_label() doesn't accidentally clear earlier metadata.
        if description is not None:
            label.description = description
        if length is not None:
            label.length = length
        if group is not None:
            label.group = group
        if access is not None:
            label.access = access
        return label

    def add_local_label(
        self,
        runtime_addr,
        name: str,
        start_addr,
        end_addr,
        *,
        move_id: int | None = None,
    ) -> Label:
        if not _is_identifier(name):
            raise LabelError(
                f"Local label name {name!r} is not a valid identifier"
            )
        move_id = self._resolve_move_id(move_id)
        label = self._get_or_create(runtime_addr)
        label.add_local_label(
            LocalLabel(name=name, start_addr=start_addr, end_addr=end_addr),
            move_id=move_id,
        )
        return label

    def add_expression(
        self,
        runtime_addr,
        expression: str,
        *,
        move_id: int | None = None,
    ) -> Label:
        if _is_identifier(expression):
            raise LabelError(
                f"{expression!r} looks like an identifier, not an expression — "
                f"use add_label() for plain names"
            )
        move_id = self._resolve_move_id(move_id)
        label = self._get_or_create(runtime_addr)
        label.add_expression(expression, move_id=move_id)
        return label

    def add_reference(
        self,
        runtime_addr,
        reference: BinaryLocation,
    ) -> Label:
        label = self._get_or_create(runtime_addr)
        label.add_reference(reference)
        return label

    def _resolve_move_id(self, move_id: int | None) -> int:
        if move_id is None:
            active = self._move_manager.active_move_ids
            move_id = active[-1] if active else BASE_MOVE_ID
        if not self._move_manager.is_valid_move_id(move_id):
            raise LabelError(
                f"unknown move id: {move_id}; valid ids depend on the "
                f"associated MoveManager"
            )
        return move_id

    def _get_or_create(self, runtime_addr) -> Label:
        runtime_addr = RuntimeAddr(runtime_addr)
        if runtime_addr not in self._labels:
            self._labels[runtime_addr] = Label(runtime_addr)
        return self._labels[runtime_addr]
